[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["rm -rf /root/.npm", "cd .. && npm install --legacy-peer-deps"]
cacheDirectories = []

[phases.build]
cmds = ["cd .. && npm run build"]

[start]
cmd = "cd .. && npm run preview -- --port $PORT"
