[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd .. && npm cache clean --force && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd .. && npm run build"]

[start]
cmd = "cd .. && npm run preview -- --port $PORT"
