[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd .. && rm -rf node_modules package-lock.json && npm install --legacy-peer-deps --no-cache"]

[phases.build]
cmds = ["cd .. && npm run build"]

[start]
cmd = "cd .. && npm run preview -- --port $PORT"
